### ISSUE TITLE
Cuisine Filter issue

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/pickpro#24]
Steps :
1) In home page click on see all button of "CUISINES"
2) There select any cuisine like say "America"
3) In sort by filters "Veg" and "Non-veg" filter is not working
When I select VEG , all the recipes are coming including NON VEG
When I select NON VEG , no records are coming even though non veg recipes are there
4) there a VEG ONLY check box as well. By selecting that also recipes are not getting filtered out to veg. instead it shows all the records.

Expected result : When User sort by VEG or NON VEG accordingly recipes should be listed.

PFA
 @![IMG_20201206_193050](https://user-images.githubusercontent.com/69690962/101282427-1dba4e00-37fb-11eb-8ef8-7e417ed4009b.jpg)

**Comment by pagumakwana** [comment]
Issued Resolved check in Beta 1.0 v

**Comment by sangeetajad** [comment]
closed
