### ISSUE TITLE
Back arrow button is not functional in Manage Address

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/pickpro#29]
Scenario :  

1) Login with user
2) Go to Manage addresses
3) Click on ADD NEW ADDESS
4) Enter all the info and add new address
5) Now click on back button on manage address which at the left hand corner

Back button is not functional or I need to click twice to go the back page 
Kindly check the back button functionality

**Comment by pagumakwana** [comment]
Will update in next build
