### ISSUE TITLE
Password issue after changing new password

### ISSUE THREAD

**Issue by sangeetajad** [pagumakwana/pickpro#34]
Scenario :
1) Click on forgot OTP, OTP will come to your email
2) Enter OTP and add new password. and click on change password

**Kindly add pop up saying that "Password has changed successfully "**

3) Now try to login with new password, I am unable login with new password. It shows that invalid login / password
this is happening because I am able to set new password with more than 8 digits but while login we required max 8 digit.
Hence kindly add validation while setting new password that max 8 digit is allowed. User should not be able add more than 8 digit while resetting new password. So that user can login with new password.

**4) Also make encypt / decrypt icon of password field functional so that user can see their password what they are entering**

**Comment by pagumakwana** [comment]
Done resolved in next build
