### ISSUE TITLE
Home screen, above and below tab bar

### ISSUE THREAD

**Issue by Edenrebello** [pagumakwana/pickpro#5]
MOST VIEWED RECIPE should be MOST VIEWED RECIPES

MOST VIEWED PRODUCT should be MOST VIEWED PRODUCTS

Top bar: 
1. Search bar is not center aligned..make it center aligned or increase the length of the search bar.
2. If user is not logged in or doesn't have a profile picture then show default profile picture icon instead of blank/ 

broken image.

In below tab bar: Product should be Products

**Comment by PallaviChapla** [comment]
All Done !!

**2.** If user is not logged in or doesn't have a profile picture then show default profile picture icon instead of blank/broken image. - **Assign this issue to the Developer**

**Comment by pagumakwana** [comment]
Implemented and updated in apk
